### ISSUE TITLE
No actions are taken in the browser

### ISSUE THREAD

**Issue by sdpmas** [nat/natbot#2]
Hi Nat, 

Super interesting work! I was trying it out and although GPT-3 generates a valid response, no actions are taken in the browser. I.e. it gets stuck in google.com and GPT-3 generates same response over and over again. Not sure if it's just me.

**Comment by nat** [comment]
Did you figure it out?

**Comment by sdpmas** [comment]
> Did you figure it out?

I got this problem only while running Chromium on a bigger display, so it seemed to be related to the positioning of elements.
